import type { INodeProperties } from 'n8n-workflow';
import {
	additionalBodyJsonField,
	imageLocator,
	labelSelectorOption,
	limitField,
	locationLocator,
	pageOption,
	serverLocator,
	serverTypeLocator,
	unwrap,
} from '../../shared/descriptions';
import { buildServerBody, mergeAdditionalJson } from '../../shared/preSend';

const showFor = { resource: ['server'] };
const showCreate = { ...showFor, operation: ['create'] };
const actionPath = (verb: string) => `=/v1/servers/{{ $parameter.serverId }}/actions/${verb}`;
// Simple actions return { action }. Composite ones (create, create_image, enable_rescue,
// rebuild, reset_password, delete) are intentionally NOT unwrapped to preserve extra fields.
const singleServerOps = [
	'get',
	'delete',
	'update',
	'attachIso',
	'detachIso',
	'changeProtection',
	'changeType',
	'createImage',
	'enableRescue',
	'disableRescue',
	'powerOff',
	'powerOn',
	'reboot',
	'rebuild',
	'reset',
	'resetPassword',
	'shutdown',
];

export const serverDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: showFor },
		options: [
			{
				name: 'Attach ISO',
				value: 'attachIso',
				action: 'Attach an ISO to a server',
				description: 'Attach an ISO to a server',
				routing: { request: { method: 'POST', url: actionPath('attach_iso') }, ...unwrap('action') },
			},
			{
				name: 'Change Protection',
				value: 'changeProtection',
				action: 'Change server protection',
				description: 'Change the delete and rebuild protection of a server',
				routing: {
					request: { method: 'POST', url: actionPath('change_protection') },
					...unwrap('action'),
				},
			},
			{
				name: 'Change Type',
				value: 'changeType',
				action: 'Change the server type',
				description: 'Change the type (size) of a server',
				routing: { request: { method: 'POST', url: actionPath('change_type') }, ...unwrap('action') },
			},
			{
				name: 'Create',
				value: 'create',
				action: 'Create a server',
				description: 'Create a new server',
				routing: {
					send: { preSend: [buildServerBody, mergeAdditionalJson] },
					request: { method: 'POST', url: '/v1/servers' },
				},
			},
			{
				name: 'Create Image',
				value: 'createImage',
				action: 'Create an image from a server',
				description: 'Create an image (snapshot or backup) from a server',
				routing: { request: { method: 'POST', url: actionPath('create_image') } },
			},
			{
				name: 'Delete',
				value: 'delete',
				action: 'Delete a server',
				description: 'Delete a server',
				routing: { request: { method: 'DELETE', url: '=/v1/servers/{{ $parameter.serverId }}' } },
			},
			{
				name: 'Detach ISO',
				value: 'detachIso',
				action: 'Detach an ISO from a server',
				description: 'Detach the attached ISO from a server',
				routing: { request: { method: 'POST', url: actionPath('detach_iso') }, ...unwrap('action') },
			},
			{
				name: 'Disable Rescue',
				value: 'disableRescue',
				action: 'Disable rescue mode',
				description: 'Disable rescue mode for a server',
				routing: {
					request: { method: 'POST', url: actionPath('disable_rescue') },
					...unwrap('action'),
				},
			},
			{
				name: 'Enable Rescue',
				value: 'enableRescue',
				action: 'Enable rescue mode',
				description: 'Enable rescue mode for a server (returns a root password)',
				routing: { request: { method: 'POST', url: actionPath('enable_rescue') } },
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a server',
				description: 'Retrieve a single server by ID',
				routing: {
					request: { method: 'GET', url: '=/v1/servers/{{ $parameter.serverId }}' },
					...unwrap('server'),
				},
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many servers',
				description: 'List servers in the project',
				routing: { request: { method: 'GET', url: '/v1/servers' }, ...unwrap('servers') },
			},
			{
				name: 'Power Off',
				value: 'powerOff',
				action: 'Power off a server',
				description: 'Cut power to a server (hard power off)',
				routing: { request: { method: 'POST', url: actionPath('poweroff') }, ...unwrap('action') },
			},
			{
				name: 'Power On',
				value: 'powerOn',
				action: 'Power on a server',
				description: 'Power on a server',
				routing: { request: { method: 'POST', url: actionPath('poweron') }, ...unwrap('action') },
			},
			{
				name: 'Reboot',
				value: 'reboot',
				action: 'Reboot a server',
				description: 'Soft-reboot a server (ACPI)',
				routing: { request: { method: 'POST', url: actionPath('reboot') }, ...unwrap('action') },
			},
			{
				name: 'Rebuild',
				value: 'rebuild',
				action: 'Rebuild a server from an image',
				description: 'Rebuild a server from an image (returns a root password)',
				routing: { request: { method: 'POST', url: actionPath('rebuild') } },
			},
			{
				name: 'Reset',
				value: 'reset',
				action: 'Reset a server',
				description: 'Cut power to and restart a server (hard reset)',
				routing: { request: { method: 'POST', url: actionPath('reset') }, ...unwrap('action') },
			},
			{
				name: 'Reset Password',
				value: 'resetPassword',
				action: 'Reset the root password',
				description: 'Reset the root password of a server (returns a new root password)',
				routing: { request: { method: 'POST', url: actionPath('reset_password') } },
			},
			{
				name: 'Shutdown',
				value: 'shutdown',
				action: 'Shut down a server',
				description: 'Send an ACPI shutdown request to a server',
				routing: { request: { method: 'POST', url: actionPath('shutdown') }, ...unwrap('action') },
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update a server',
				description: 'Update an existing server (name and labels)',
				routing: {
					request: { method: 'PUT', url: '=/v1/servers/{{ $parameter.serverId }}' },
					...unwrap('server'),
				},
			},
		],
		default: 'getAll',
	},

	serverLocator({ ...showFor, operation: singleServerOps }, { inPath: true }),

	// Create
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: showCreate },
		placeholder: 'e.g. web-01',
		routing: { send: { type: 'body', property: 'name', value: '={{ $value }}' } },
		description: 'A unique hostname for the server (RFC 1123 compliant)',
	},
	serverTypeLocator({ ...showCreate }, { property: 'server_type' }),
	imageLocator({ ...showCreate }, { property: 'image' }),
	locationLocator({ ...showCreate }, { property: 'location', required: false }),
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: showCreate },
		options: [
			{
				displayName: 'Automount Volumes',
				name: 'automount',
				type: 'boolean',
				default: false,
				description: 'Whether to auto-mount the attached volumes',
			},
			{
				displayName: 'Datacenter',
				name: 'datacenter',
				type: 'string',
				default: '',
				placeholder: 'e.g. nbg1-dc3',
				description: 'The datacenter name to create the server in (alternative to Location)',
			},
			{
				displayName: 'Enable IPv4',
				name: 'enableIpv4',
				type: 'boolean',
				default: true,
				description: 'Whether to attach a public IPv4 address',
			},
			{
				displayName: 'Enable IPv6',
				name: 'enableIpv6',
				type: 'boolean',
				default: true,
				description: 'Whether to attach a public IPv6 address',
			},
			{
				displayName: 'Firewall IDs',
				name: 'firewalls',
				type: 'string',
				default: '',
				placeholder: 'e.g. 38,42',
				description: 'Comma-separated firewall IDs to apply to the server',
			},
			{
				displayName: 'Labels (JSON)',
				name: 'labels',
				type: 'json',
				default: '{}',
				description: 'Labels to attach to the server as a JSON object',
			},
			{
				displayName: 'Network IDs',
				name: 'networks',
				type: 'string',
				default: '',
				placeholder: 'e.g. 4711',
				description: 'Comma-separated network IDs to attach the server to',
			},
			{
				displayName: 'Placement Group ID',
				name: 'placementGroup',
				type: 'string',
				default: '',
				placeholder: 'e.g. 1',
				description: 'The ID of the placement group to add the server to',
			},
			{
				displayName: 'SSH Keys',
				name: 'sshKeys',
				type: 'string',
				default: '',
				placeholder: 'e.g. my-key,123',
				description: 'Comma-separated SSH key names or IDs to add to the server',
			},
			{
				displayName: 'Start After Create',
				name: 'startAfterCreate',
				type: 'boolean',
				default: true,
				description: 'Whether to start the server immediately after creating it',
			},
			{
				displayName: 'User Data',
				name: 'userData',
				type: 'string',
				typeOptions: { rows: 4 },
				default: '',
				placeholder: '#cloud-config\n...',
				description: 'Cloud-init user data to run on first boot',
			},
		],
	},
	additionalBodyJsonField({ ...showFor, operation: ['create', 'update'] }),

	// Update
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showFor, operation: ['update'] } },
		routing: { send: { type: 'body', property: 'name', value: '={{ $value }}' } },
		description: 'A new unique hostname for the server',
	},

	// Attach ISO
	{
		displayName: 'ISO',
		name: 'iso',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { ...showFor, operation: ['attachIso'] } },
		placeholder: 'e.g. virtio-win.iso or 4711',
		routing: { send: { type: 'body', property: 'iso', value: '={{ $value }}' } },
		description: 'The ID or name of the ISO to attach',
	},

	// Change Type
	serverTypeLocator({ ...showFor, operation: ['changeType'] }, { property: 'server_type' }),
	{
		displayName: 'Upgrade Disk',
		name: 'upgradeDisk',
		type: 'boolean',
		default: false,
		displayOptions: { show: { ...showFor, operation: ['changeType'] } },
		routing: { send: { type: 'body', property: 'upgrade_disk', value: '={{ $value }}' } },
		description: 'Whether to also increase the disk size (irreversible; blocks downgrades)',
	},

	// Create Image
	{
		displayName: 'Type',
		name: 'imageType',
		type: 'options',
		options: [
			{ name: 'Snapshot', value: 'snapshot' },
			{ name: 'Backup', value: 'backup' },
		],
		default: 'snapshot',
		displayOptions: { show: { ...showFor, operation: ['createImage'] } },
		routing: { send: { type: 'body', property: 'type', value: '={{ $value }}' } },
		description: 'The type of image to create',
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showFor, operation: ['createImage'] } },
		routing: { send: { type: 'body', property: 'description', value: '={{ $value }}' } },
		description: 'A description for the created image',
	},

	// Enable Rescue
	{
		displayName: 'Rescue Type',
		name: 'rescueType',
		type: 'options',
		options: [{ name: 'Linux 64-Bit', value: 'linux64' }],
		default: 'linux64',
		displayOptions: { show: { ...showFor, operation: ['enableRescue'] } },
		routing: { send: { type: 'body', property: 'type', value: '={{ $value }}' } },
		description: 'The rescue system to boot into',
	},
	{
		displayName: 'SSH Key IDs',
		name: 'rescueSshKeys',
		type: 'string',
		default: '',
		displayOptions: { show: { ...showFor, operation: ['enableRescue'] } },
		placeholder: 'e.g. 123,456',
		routing: {
			send: {
				type: 'body',
				property: 'ssh_keys',
				value: '={{ $value.split(",").map(s => Number(s.trim())).filter(n => !isNaN(n)) }}',
			},
		},
		description: 'Comma-separated SSH key IDs to add to the rescue system',
	},

	// Rebuild
	imageLocator({ ...showFor, operation: ['rebuild'] }, { property: 'image' }),

	// Change Protection
	{
		displayName: 'Delete Protection',
		name: 'deleteProtection',
		type: 'boolean',
		default: true,
		displayOptions: { show: { ...showFor, operation: ['changeProtection'] } },
		routing: { send: { type: 'body', property: 'delete', value: '={{ $value }}' } },
		description: 'Whether the server is protected against deletion',
	},
	{
		displayName: 'Rebuild Protection',
		name: 'rebuildProtection',
		type: 'boolean',
		default: true,
		displayOptions: { show: { ...showFor, operation: ['changeProtection'] } },
		routing: { send: { type: 'body', property: 'rebuild', value: '={{ $value }}' } },
		description: 'Whether the server is protected against rebuild',
	},

	limitField({ ...showFor, operation: ['getAll'] }),
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { ...showFor, operation: ['getAll'] } },
		options: [
			pageOption,
			labelSelectorOption,
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				routing: { send: { type: 'query', property: 'name', value: '={{ $value }}' } },
				description: 'Filter servers by their exact name',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Initializing', value: 'initializing' },
					{ name: 'Off', value: 'off' },
					{ name: 'Running', value: 'running' },
					{ name: 'Starting', value: 'starting' },
					{ name: 'Stopping', value: 'stopping' },
				],
				default: 'running',
				routing: { send: { type: 'query', property: 'status', value: '={{ $value }}' } },
				description: 'Filter servers by status',
			},
		],
	},
];
